/** Generated by scripts/sync-craft-village-media.mjs — ảnh trong public/images/gallery/ */

import { gomPhuocTichGalleryImages } from "@/data/gom-phuoc-tich-gallery";

export const langHuongThuyXuanGalleryImages = [
  "5 (1).jpg",
  "5 (1).png",
  "5 (2).jpg",
  "5 (2).png",
  "5 (3).jpg",
  "5 (3).png",
  "5 (4).jpg",
  "5 (4).png",
  "5 (5).jpg",
  "5 (5).png",
  "5 (6).jpg",
  "5 (7).jpg",
  "5 (8).jpg",
  "5 (9).jpg",
].map((file, i) => ({
  src: `/images/gallery/huong-thuy-xuan/${encodeURIComponent(file)}`,
  alt: `Làng hương trầm Thủy Xuân — ảnh ${i + 1}`,
}));

export const hoaGiayThanhTienGalleryImages = [
  "2 (1).jpg",
  "2 (1).png",
  "2 (2).jpg",
  "2 (2).png",
  "2 (3).jpg",
  "2 (4).jpg",
  "2 (5).JPG",
  "2 (6).jpg",
  "2 (7).jpg",
  "2 (8).jpg",
  "6HGyvV2TniZ.png",
].map((file, i) => ({
  src: `/images/gallery/giay-thanh-tien/${encodeURIComponent(file)}`,
  alt: `Làng hoa giấy Thanh Tiên — ảnh ${i + 1}`,
}));

export const dengALuoiGalleryImages = [
  "4 (1).jpg",
  "4 (2).jpg",
  "4 (3).jpg",
  "4 (4).jpg",
  "4 (5).jpg",
  "4 (6).jpg",
  "4 (7).jpg",
  "4 (8).jpg",
  "4 (9).jpg",
  "4 (10).jpg",
].map((file, i) => ({
  src: `/images/gallery/det-zeng/${encodeURIComponent(file)}`,
  alt: `Nghề dệt Dèng A Lưới — ảnh ${i + 1}`,
}));

export const tranhLangSinhGalleryImages = [
  "2 (1).jpg",
  "2 (1).png",
  "2 (2).png",
  "2 (3).png",
  "2 (4).png",
  "2 (5).png",
  "2 (6).png",
  "2 (7).png",
  "2 (8).png",
  "2 (9).png",
  "2 (10).png",
  "2 (11).png",
  "2 (12).png",
].map((file, i) => ({
  src: `/images/gallery/tranh-lang-sinh/${encodeURIComponent(file)}`,
  alt: `Tranh làng Sình — ảnh ${i + 1}`,
}));

export const quatGiayBaoVinhGalleryImages = [
  "1.png",
  "2.jpg",
  "3.jpg",
  "4.jpg",
].map((file, i) => ({
  src: `/images/gallery/quat-giay-bao-vinh/${encodeURIComponent(file)}`,
  alt: `Nghề làm quạt giấy Bảo Vinh — ảnh ${i + 1}`,
}));

export const longCungDinhHueGalleryImages = [
  "1.jpg",
  "2.jpg",
  "3.jpg",
].map((file, i) => ({
  src: `/images/gallery/long-cung-dinh/${encodeURIComponent(file)}`,
  alt: `Nghề làm lọng cung đình Huế — ảnh ${i + 1}`,
}));

export type CraftGalleryImage = { src: string; alt: string };

/** Ảnh gallery theo slug làng nghề (dùng trang listing, thư viện, v.v.). */
export const craftVillageGalleryBySlug: Record<string, CraftGalleryImage[]> = {
  "lang-huong-thuy-xuan": langHuongThuyXuanGalleryImages,
  "hoa-giay-thanh-tien": hoaGiayThanhTienGalleryImages,
  "deng-a-luoi": dengALuoiGalleryImages,
  "tranh-lang-sinh": tranhLangSinhGalleryImages,
  "quat-giay-bao-vinh": quatGiayBaoVinhGalleryImages,
  "long-cung-dinh-hue": longCungDinhHueGalleryImages,
  "gom-phuoc-tich": gomPhuocTichGalleryImages,
};

/** Ghép caption từ `villages.ts` với ảnh thật trong thư mục gallery. */
export function getVillageGalleryMoments(slug: string, captions: string[]): { caption: string; src: string; alt: string }[] {
  const images = craftVillageGalleryBySlug[slug] ?? [];
  return captions.map((caption, i) => {
    const img = images[i];
    return {
      caption,
      src: img?.src ?? "",
      alt: img?.alt ?? caption,
    };
  });
}
